### ISSUE TITLE
Checksum is wrong

### ISSUE THREAD

**Issue by josephktcheung** [Instabug/Instabug-SP#24]
### Steps to Reproduce the Problem
Setup a project and include Instabug-SP via Swift package manager.

### Expected Behavior
It loads the Instabug framework into the project

### Actual Behavior
```
checksum of downloaded artifact of binary target 'Instabug' (72973ac4472099220a414068fd315c11c5698a926e79339ed526f68fa9810ef4) does not match checksum specified by the manifest (ccda67f47b40ab82c25f63af798a6665057fdc8e35a249114b9c7b4128011ca3)
```

### Instabug integration code
*Make sure to remove your app token.*

### SDK Version
11.5.0
### XCode Version
14.1

**Comment by moisesolmedo-okta** [comment]
Getting the same issue.

**Comment by krevis-figma** [comment]
Same here.

**Comment by RSickenberg** [comment]
Same issue ...

**Comment by xmollv** [comment]
Yeah facing the same issue over here!

**Comment by ahmedsalah196** [comment]
Please accept our sincere apology for the inconvenience
We can now confirm that this issue has been fixed
