### ISSUE TITLE
This doesn't work. Is it time to leave instabug? 

### ISSUE THREAD

**Issue by adamdahan** [Instabug/Instabug-SP#26]

**Comment by adamdahan** [comment]
I feel like your product is getting worse and worse. Time to find alternatives.

**Comment by mzsoliman** [comment]
Sorry to hear that @adamdahan do you mind adding more details regarding what exactly doesn't work?
I saw your other ticket related to supporting SPM, is that it?

**Comment by adamdahan** [comment]
Just try to use SPM to install it on Xcode 14.2 lots of issues.
