### ISSUE TITLE
[Xcode 16.1] Incorrect checksum for the new package version

### ISSUE THREAD

**Issue by jpszczerba** [Instabug/Instabug-SP#39]
### Steps to Reproduce the Problem
1. Update the package to 13.4.3 in a project.
2. Xcode fetches the zip and calculates a checksum.
3. It fails with error: `
Showing All Errors Only
`checksum of downloaded artifact of binary target 'Instabug' (c4231464b08c3ff52eb3195759e3fa0102671346d9cd1ce47f177b1345ce9ec3) does not match checksum specified by the manifest (c00b43a1194cdd382b1d6ed42519a125ee09863edcc3103827fe30cdb4abe4d3)`

Also confirmed by checking the checksum of the zip manually:
```
❯ swift package compute-checksum Instabug-XCFramework.zip
c4231464b08c3ff52eb3195759e3fa0102671346d9cd1ce47f177b1345ce9ec3
```

### Expected Behavior
Correct checksum in the package definition.

### Actual Behavior
Incorrect checksum in the package definition.

### SDK Version
13.4.3

### iOS Version
n/a

### Device Model
n/a

**Comment by AhmedAshraf605** [comment]
Hi @jpszczerba 
We are working on a fix

**Comment by jpszczerba** [comment]
Thank you!

**Comment by AhmedAshraf605** [comment]
@jpszczerba This issue should be fixed now, Thanks for your contribution 🙏🏻
