### ISSUE TITLE
Getting a failed to extract error

### ISSUE THREAD

**Issue by AndrewSB** [Instabug/Instabug-SP#5]
<img width="685" alt="Screen Shot 2020-12-06 at 4 57 08 AM" src="https://user-images.githubusercontent.com/3814772/101277053-8c59c600-377f-11eb-8fc2-1f1e13a46b2f.png">

I'm targeting the 10.1.0 release, not sure why I'm getting this error or how to get more verbose messaging. Is this a KP?

**Comment by yousefhamza** [comment]
Hi @AndrewSB
Clearing "Derived Data" should resolve this.

**Comment by AndrewSB** [comment]
d'oh. that did the trick. thanks @yousefhamza

**Comment by BrentMifsud** [comment]
I am also getting this issue.

Running file -> swift packages -> reset package cache seems to fix it temporarily. but making any large directory changes or updating other dependencies seems to trigger it to happen again.
