### ISSUE TITLE
Errors when shipping

### ISSUE THREAD

**Issue by jbouaziz** [Instabug/Instabug-SP#8]
### Steps to Reproduce the Problem
Archive and upload a project containing Instabug installed through the SPM.

### Expected Behavior
Apple shouldn't give me a hard time.

### Actual Behavior
Apple is giving me a hard time
![image](https://user-images.githubusercontent.com/3008860/102106254-a2771e80-3e30-11eb-9783-2aed386c2c2a.png)
![image](https://user-images.githubusercontent.com/3008860/102106277-a86cff80-3e30-11eb-93a9-41f9fb968941.png)

### Instabug integration code
I was previously using Cocoapods for the Instabug integration and made sure that the `Instabug.framework` file isn't in my project anywhere else that through SPM.
``` swift
#if !targetEnvironment(macCatalyst)
Instabug.welcomeMessageMode = .automatic
Instabug.start(
    withToken: "-----",
    invocationEvents: [.shake, .screenshot]
)
#endif
```

### SDK Version
10.1.0

### iOS Version
12+

### Device Model
"Any iOS Device (arm64)" build

**Comment by Kmohamed** [comment]
@jbouaziz We are very sorry for that hard time.
Could you check this [comment](https://github.com/Instabug/Instabug-iOS/issues/330#issuecomment-739475832) I think it maybe related

**Comment by jbouaziz** [comment]
@Kmohamed thanks for getting back at me. Due to a timed release, I had to switch back to cocoapods for the time being so I won't be able to test that. I'll wait until we don't need to use any workarounds to use Instabug-SP. Thanks!

**Comment by warpling** [comment]
I'm also still experiencing this with SPM.

**Comment by yousefhamza** [comment]
Hi @warpling 👋

SPM still have some rough edges, like this error. Check this for more details: https://github.com/Instabug/Instabug-iOS/issues/330#issuecomment-739475832
