### ISSUE TITLE
Package Resolution Failed

### ISSUE THREAD

**Issue by RamblinWreck77** [Instabug/Instabug-SP#9]
-Xcode 12.3
-Try and add InstabugSP swift package
-Add fails with the following error:

 
<img width="719" alt="Screen Shot 2020-12-29 at 12 56 54 PM" src="https://user-images.githubusercontent.com/22692130/103303983-6ec1fa00-49d5-11eb-8705-1c19657aa36f.png">

Has anything changed with your hosted .zip archive recently? It was working fine back when SPM support launched.

**Comment by RamblinWreck77** [comment]
Wow... 

So removing the dependency, File/Swift Packages/Reset Package Caches, then letting it finish, then re-adding the dependency fixed the issue.

Looks like this was just another dumb Xcode bug, thanks Apple! Closing this and leaving it for future users to find :)

**Comment by Kmohamed** [comment]
Perfect, I am happy that everything went well.
